# =============================================================================
# NIS Client Configuration (yp.conf)
# =============================================================================
# Definit comment le client NIS trouve son serveur.
# =============================================================================

# Domain NIS
domain localdomain

# Server NIS - adresse du container nis-server sur le network docker
server 172.20.0.2

# Fallback: broadcast si server non trouve (optionnel)
broadcast